=== taliesins/Thinktecture.IdentityServer.v2/src/OnPremise/WebSite/Deployment/PowershellModules/configuration.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="configuration">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="sites" type="sites" minOccurs="0" maxOccurs="1">
          <xs:unique name="UniqueAppPoolNames">
            <xs:selector xpath=".//appPool" />
            <xs:field xpath="@name" />
          </xs:unique>
        </xs:element>
        <xs:element name="services" type="services" minOccurs="0" maxOccurs="1">
          <xs:unique name="UniqueServiceName">
            <xs:selector xpath="./*" />
            <xs:field xpath="name" />
          </xs:unique>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="defaultHost" default="localhost" />
      <xs:attribute name="componentName" use="required">
        <xs:annotation>
          <xs:documentation>componentName is a destination folder name for the application</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value=".+" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="sites">
    <xs:sequence>
      <xs:element name="site" type="site" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="services">
    <xs:sequence>
      <xs:element name="NServiceBus" type="NServiceBus" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="WindowsService" type="WindowsService" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="TopshelfService" type="TopshelfService" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="site">
    <xs:all>
      <xs:element name="bindings" type="bindings" minOccurs="0" maxOccurs="1" />
      <xs:element name="appPool" type="appPool" minOccurs="0" maxOccurs="1" />
      <xs:element name="applications" type="applications" minOccurs="0" maxOccurs="1">
        <xs:unique name="UniqueApplicationAlias">
          <xs:selector xpath="application" />
          <xs:field xpath="@alias" />
        </xs:unique>
        <xs:unique name="UniqueApplicationPhysicalPath">
          <xs:selector xpath="application" />
          <xs:field xpath="@physicalPath" />
        </xs:unique>
      </xs:element>
      <xs:element name="virtualDirectories" type="virtualDirectories" minOccurs="0" maxOccurs="1" />
    </xs:all>
    <xs:attribute name="path" default="c:\inetpub\wwwroot" />
    <xs:attribute name="name" default="easyJet.Services.Container" />
    <xs:attribute name="containerOnly" default="false" type="xs:boolean" />
  </xs:complexType>

  <xs:complexType name="virtualDirectories">
    <xs:sequence>
      <xs:element name="virtualDirectory" type="virtualDirectory" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="applications">
    <xs:sequence>
      <xs:element name="application" type="application" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="virtualDirectory">
    <xs:attribute name="alias" use="required" />
    <xs:attribute name="physicalPath" default="."/>
  </xs:complexType>

  <xs:complexType name="application">
    <xs:complexContent>
      <xs:extension base="virtualDirectory">
        <xs:sequence>
          <xs:element name="appPool" type="appPool" minOccurs="0" maxOccurs="1" />
          <xs:element name="applications" type="applications" minOccurs="0" maxOccurs="1" />
          <xs:element name="virtualDirectories" type="virtualDirectories" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="bindings">
    <xs:sequence>
      <xs:element name="binding" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:all>
            <xs:element name="ssl" minOccurs="0">
              <xs:complexType>
                <xs:attribute name="thumbprint" />
              </xs:complexType>
            </xs:element>
          </xs:all>
          <xs:attribute name="protocol" type="protocol" use="required" />
          <xs:attribute name="information" type="xs:string" use="required" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="protocol">
    <xs:restriction base="xs:string">
      <xs:enumeration value="http" />
      <xs:enumeration value="https" />
      <xs:enumeration value="net.tcp" />
      <xs:enumeration value="net.pipe" />
      <xs:enumeration value="net.msmq" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="appPool">
    <xs:all>
      <xs:element name="account" type="xs:string" minOccurs="0" maxOccurs="1" />
      <xs:element name="password" type="xs:string" minOccurs="0" maxOccurs="1" />
      <xs:element name="properties" type="appPoolProperties" minOccurs="0" maxOccurs="1" />
    </xs:all>
    <xs:attribute name="name" use="required" />
    <xs:attribute name="frameworkVersion" type="frameworkVersion" default="v4.0" />
    <xs:attribute name="enable32Bit" type="xs:boolean" default="false" />
    <xs:attribute name="managedPipelineMode" type="managedPipelineMode" default="Integrated" />
  </xs:complexType>

  <xs:complexType name="appPoolProperties">
    <xs:sequence>
      <xs:element name="property" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="path" use="required" />
          <xs:attribute name="value" use="required" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="frameworkVersion">
    <xs:restriction base="xs:string">
      <xs:enumeration value="v2.0" />
      <xs:enumeration value="v4.0" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="managedPipelineMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Classic" />
      <xs:enumeration value="Integrated" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="service">
    <xs:sequence>
      <xs:element name="name" minOccurs="0" maxOccurs="1" type="xs:string" />
      <xs:element name="displayName" minOccurs="0" maxOccurs="1" type="xs:string"  />
      <xs:element name="account" minOccurs="0" maxOccurs="1" type="xs:string" />
      <xs:element name="password" minOccurs="0" maxOccurs="1" type="xs:string" />
      <xs:element name="serviceStartupType" type="serviceStartupType" default="delayed-auto" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="serviceStartupType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="boot">
        <xs:annotation>
          <xs:documentation>Wil start the service at the boot time</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="system" />
      <xs:enumeration value="auto" />
      <xs:enumeration value="demand" />
      <xs:enumeration value="disabled" />
      <xs:enumeration value="error" />
      <xs:enumeration value="delayed-auto" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="WindowsService" >
    <xs:complexContent mixed="false">
      <xs:extension base="service">
        <xs:attribute name="path" type="xs:string" />
        <xs:attribute name="srvany" type="xs:boolean" default="false" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="TopshelfService" >
    <xs:complexContent mixed="false">
      <xs:extension base="service">
        <xs:attribute name="path" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="NServiceBus" >
    <xs:complexContent mixed="false">
      <xs:extension base="service">
        <xs:sequence>
          <xs:element name="profiles" type="NServiceBusProfiles" minOccurs="0" />
          <xs:element name="queues" type="NServiceBusQueues" minOccurs="0" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="NServiceBusProfiles">
    <xs:sequence>
      <xs:element name="profile" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="NServiceBusQueues">
    <xs:sequence>
      <xs:element name="queue" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== taliesins/Thinktecture.IdentityServer.v2/src/OnPremise/WebSite/Deployment/configuration.xml
<?xml version="1.0" encoding="utf-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PowershellModules/configuration.xsd" componentName="WebSite">
  <sites>
    <site containerOnly="false" name="Thinktecture.IdentityServer" path=".">
      <appPool enable32Bit="false" frameworkVersion="v4.0" name="Thinktecture.IdentityServer" managedPipelineMode="Integrated">
        <properties>
          <property path="processModel.loadUserProfile" value="false" />
          <property path="processModel.IdleTimeout" value="0:20:0" />
          <property path="recycling.periodicRestart.time" value="0" />
        </properties>
      </appPool>
      <bindings>
        <binding protocol="https" information="{FrontEnd.HostHeader}:443:">
          <ssl thumbprint="{FrontEnd.HttpsCertificateThumbprint}"/>
        </binding>
      </bindings>
    </site>
  </sites>
</configuration>
